/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fitnesshub;

import java.awt.FileDialog;
import java.awt.Image;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.CopyOption;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.filechooser.FileSystemView;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class ADMINMEMBERDETAILS extends javax.swing.JPanel implements FocusListener {

    /**
     * Creates new form ADMINMEMBERDETAILS
     */
    ADMINPAGE d;
    
    
            PreparedStatement statement;
        Connection connection;
        ResultSet set;
        int MEMBERID;
        
        String s1,s2,STARTINGDATE,PASSWORD,ENDINGDATE,REMAININGDAYS,FIRSTNAME,MIDDLENAME,LASTNAME,GENDER,DATEOFBIRTH,BLOODGROUP,ADDRESS,CITY,STATE,CONTACTNO,EMAILID,DATEOFJOINING,TIMINGS,BATCH,MEMBERSHIPTYPE,MEMBERSHIPSTATUS;
         float SALARY;
         int row;
         Vector<String> v1;
          Vector<Vector> v2;
          DefaultTableModel dtm;

          int sn=1;
          
    public ADMINMEMBERDETAILS (ADMINPAGE d) {
        initComponents();
        
            jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
            
            v1=new Vector();
            v2=new Vector();

          v1.add("MEMBERID");
          v1.add("FIRSTNAME");
          v1.add("MIDDLENAME");
          v1.add("LASTNAME");
          v1.add("GENDER");
          v1.add("DATEOFBIRTH");
          v1.add("BLOODGROUP");
          v1.add("ADDRESS");
          v1.add("CITY");
          v1.add("STATE");
          v1.add("CONTACTNO");
          v1.add("EMAILID");
          v1.add("MEMBERSHIPTYPE");
          v1.add("MEMBERSHIPSTATUS");
          v1.add("STARTINGDATE");
          v1.add("ENDINGDATE");
          v1.add("REMAININGDAYS");

        try
        {
          Class.forName("com.mysql.jdbc.Driver");
         connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/fitness_hub","root","1234");  
        }
        catch(ClassNotFoundException ex)
        {
            ex.printStackTrace();
        }
        catch(SQLException e)
        {
            e.printStackTrace();
        }

        this.d=d;
        jTextField22.addFocusListener(this);
        jTextField14.addFocusListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField14 = new javax.swing.JTextField();
        SEARCH = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        LOADALL = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        REGISTER = new javax.swing.JButton();
        EXIT = new javax.swing.JButton();
        UPDATE = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ADDWORKOUT = new javax.swing.JButton();
        ADDDIET = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        UPLOADPHOTO = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jRadioButton1.setBackground(new java.awt.Color(0, 51, 51));
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("BY ID");

        jRadioButton2.setBackground(new java.awt.Color(0, 51, 51));
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("BY NAME");

        SEARCH.setBackground(new java.awt.Color(0, 51, 51));
        SEARCH.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        SEARCH.setForeground(new java.awt.Color(255, 255, 255));
        SEARCH.setText("SEARCH ");
        SEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCHActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "SNO", "MEMBERID", "FIRST NAME", "MIDDLENAME", "LASTNAME", "GENDER", "DATEOFBIRTH", "BLOODGROUP", "ADDRESS", "CITY", "STATE", "CONTACTNO", "EMAIL", "MEMBERSHIPTYPE", "MEMBERSHIPDETAILS", "STARTINGDATE", "ENDINGDATE", "REMAININGDAYS"
            }
        ));
        jTable1.setIntercellSpacing(new java.awt.Dimension(10, 1));
        jScrollPane1.setViewportView(jTable1);

        LOADALL.setBackground(new java.awt.Color(0, 51, 51));
        LOADALL.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        LOADALL.setForeground(new java.awt.Color(255, 255, 255));
        LOADALL.setText("LOAD ALL MEMBERS");
        LOADALL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOADALLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(SEARCH)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addComponent(LOADALL)))
                        .addGap(0, 138, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SEARCH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LOADALL)
                .addGap(23, 23, 23))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, 397));

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MEMBERSHIP DETAILS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("MEMBERSHIP TYPE :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("STARTING DATE :");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("MEMBERSHIP STATUS :");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("ENDING DATE :");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("REMAINING DAYS :");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 MONTH", "3MONTHS", "6 MONTHS", "12 MONTHS" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVE", "NOT ACTIVE", " ", " " }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jTextField7.setText("DD//MM//YYYY");

        jTextField8.setText("DD//MM//YYYY");

        REGISTER.setBackground(new java.awt.Color(0, 51, 51));
        REGISTER.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        REGISTER.setForeground(new java.awt.Color(255, 255, 255));
        REGISTER.setText("REGISTER");
        REGISTER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTERActionPerformed(evt);
            }
        });

        EXIT.setBackground(new java.awt.Color(0, 51, 51));
        EXIT.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        EXIT.setForeground(new java.awt.Color(255, 255, 255));
        EXIT.setText("EXIT");

        UPDATE.setBackground(new java.awt.Color(0, 51, 51));
        UPDATE.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        UPDATE.setForeground(new java.awt.Color(255, 255, 255));
        UPDATE.setText("UPDATE");
        UPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(REGISTER)
                        .addGap(56, 56, 56)
                        .addComponent(UPDATE)
                        .addGap(57, 57, 57)
                        .addComponent(EXIT)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jComboBox1)
                        .addGap(1, 1, 1))
                    .addComponent(jLabel10))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(REGISTER)
                    .addComponent(UPDATE)
                    .addComponent(EXIT))
                .addGap(65, 65, 65))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, -1, -1));

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONTACT INFORMATION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ADDRESS :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CITY :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("STATE :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("EMAIL ID :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CONTACT NO :");

        ADDWORKOUT.setBackground(new java.awt.Color(0, 51, 51));
        ADDWORKOUT.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ADDWORKOUT.setForeground(new java.awt.Color(255, 255, 255));
        ADDWORKOUT.setText("ADD WORKOUT");
        ADDWORKOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDWORKOUTActionPerformed(evt);
            }
        });

        ADDDIET.setBackground(new java.awt.Color(0, 51, 51));
        ADDDIET.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ADDDIET.setForeground(new java.awt.Color(255, 255, 255));
        ADDDIET.setText("ADD DIET");
        ADDDIET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDDIETActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(ADDWORKOUT)
                        .addGap(100, 100, 100)
                        .addComponent(ADDDIET)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ADDWORKOUT)
                    .addComponent(ADDDIET))
                .addGap(24, 24, 24))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 610, 370));

        jPanel5.setBackground(new java.awt.Color(0, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PERSONAL INFORMATION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("FIRST NAME :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("BLOOD GROUP :");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("MIDDLE NAME :");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("LAST NAME :");

        UPLOADPHOTO.setBackground(new java.awt.Color(0, 51, 51));
        UPLOADPHOTO.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        UPLOADPHOTO.setForeground(new java.awt.Color(255, 255, 255));
        UPLOADPHOTO.setText("UPLOAD PHOTO");
        UPLOADPHOTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPLOADPHOTOActionPerformed(evt);
            }
        });

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("PHOTO");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("DATE OF BIRTH :");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("MEMBER ID : ");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("GENDER :");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("PASSWORD :");

        jTextField22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField22ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(292, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(231, 231, 231))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(UPLOADPHOTO)
                    .addGap(87, 87, 87)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel16)
                                .addComponent(jLabel18)
                                .addComponent(jLabel23))
                            .addGap(33, 33, 33)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel21)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(22, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(58, 58, 58))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(193, 193, 193)
                            .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel16)
                                .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18)
                                .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel23))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel21)
                                .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(197, 197, 197)
                            .addComponent(UPLOADPHOTO)))
                    .addContainerGap(45, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1383, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 867, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void REGISTERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTERActionPerformed
        
        try
        {
          statement=connection.prepareStatement("insert into memberdetails values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
         
          MEMBERID=Integer.parseInt(jTextField22.getText());
          PASSWORD=jTextField21.getText();
          FIRSTNAME=jTextField15.getText();
          MIDDLENAME=jTextField16.getText();
          LASTNAME=jTextField17.getText();
          GENDER=jTextField18.getText();
          DATEOFBIRTH=jTextField19.getText();
          BLOODGROUP=jTextField20.getText();
          ADDRESS=jTextField2.getText();
          CITY=jTextField3.getText();
          STATE=jTextField4.getText();
          CONTACTNO=jTextField5.getText();
          EMAILID=jTextField6.getText();
          s1=(String) jComboBox1.getSelectedItem();
          s2=(String) jComboBox2.getSelectedItem();
          STARTINGDATE=jTextField7.getText();
          ENDINGDATE=jTextField8.getText();
          REMAININGDAYS=jTextField9.getText();
          
         
          
          statement.setInt(1,MEMBERID);
          statement.setString(2,FIRSTNAME);
          statement.setString(3,MIDDLENAME);
          statement.setString(4,LASTNAME);
          statement.setString(5,GENDER);
          statement.setString(6,DATEOFBIRTH);
          statement.setString(7,BLOODGROUP);
          statement.setString(8,ADDRESS);
          statement.setString(9,CITY);
          statement.setString(10,STATE);
          statement.setString(11,CONTACTNO);
          statement.setString(12,EMAILID);
          statement.setString(13,s1);
          statement.setString(14,s2);
          statement.setString(15,STARTINGDATE);
          statement.setString(16,ENDINGDATE);
          statement.setString(17,REMAININGDAYS);
           statement.setString(18,PASSWORD);
          statement.executeUpdate();

        }
        catch(SQLException e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_REGISTERActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
     String s1;
       
       s1=(String) jComboBox2.getSelectedItem();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        String s2;
       
       s2=(String) jComboBox2.getSelectedItem();
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void ADDWORKOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDWORKOUTActionPerformed
       ADDWORKOUT AW=new ADDWORKOUT();
       AW.setVisible(true);
          d.dispose(); 
       
    }//GEN-LAST:event_ADDWORKOUTActionPerformed

    private void ADDDIETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDDIETActionPerformed
        ADDDIET AD=new ADDDIET();
        AD.setVisible(true);
            d.dispose(); 
    }//GEN-LAST:event_ADDDIETActionPerformed

    private void jTextField22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField22ActionPerformed

    private void UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEActionPerformed
        
        try
        {
          statement=connection.prepareStatement("update memberdetails set FIRSTNAME=? , MIDDLENAME=?, LASTNAME=?,GENDER=?,DATEOFBIRTH=?, BLOODGROUP=?,ADDRESS=?,CITY=?,STATE=?,CONTACTNO=?,EMAILID=?, MEMBERSHIPTYPE=?,MEMBERSHIPSTATUS=?,STARTINGDATE=?, ENDINGDATE=?,REMAININGDAYS=? ,PASSWORD=? where MEMBERID=?");
          
          set=statement.executeQuery();
          while(set.next())
          {
             MEMBERID=set.getInt(1);
               
              FIRSTNAME=set.getString(2); 
              MIDDLENAME=set.getString(3); 
              LASTNAME=set.getString(4); 
              GENDER=set.getString(5); 
              DATEOFBIRTH=set.getString(6); 
              BLOODGROUP=set.getString(7); 
              ADDRESS=set.getString(8); 
              CITY=set.getString(9); 
              STATE=set.getString(10); 
              CONTACTNO=set.getString(11); 
             EMAILID=set.getString(12); 
              String s1 = set.getString(14);
              String s2 = set.getString(15);
              String STARTINGDATE = set.getString(16);
              String ENDINGDATE = set.getString(17);
              String REMAININGDAYS = set.getString(18);
              PASSWORD=set.getString(19);
            
              if(s1.equals("1 MONTH"))
              {
                  jComboBox1.setSelectedIndex(1);
              }
              else if(s1.equals("3 MONTHS"))
              {
                  jComboBox1.setSelectedIndex(2);
              }
              else if(s1.equals("6 MONTHS"))
              {
                  jComboBox1.setSelectedIndex(3);
              }
              else if(s1.equals("12 MONTHS"))
              {
                  jComboBox1.setSelectedIndex(4);
              }
            
           jTextField22.setText(String.valueOf(MEMBERID));
               jTextField21.setText(PASSWORD);
               jTextField15.setText(FIRSTNAME);
               jTextField16.setText(MIDDLENAME);
               jTextField17.setText(LASTNAME);
               jTextField18.setText(GENDER);
               jTextField19.setText(DATEOFBIRTH);
               jTextField20.setText(BLOODGROUP);
               jTextField2.setText(ADDRESS);
               jTextField3.setText(CITY);
               jTextField4.setText(STATE);
               jTextField5.setText(CONTACTNO);
               jTextField6.setText(EMAILID);
                jTextField7.setText(STARTINGDATE);
                 jTextField8.setText(ENDINGDATE);
                  jTextField9.setText(REMAININGDAYS);
          }
         
        }
        catch(SQLException e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_UPDATEActionPerformed

    private void SEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCHActionPerformed
        
        try
        {
          statement=connection.prepareStatement("select * from memberdetails where MEMBERID=?");
            MEMBERID=Integer.parseInt(jTextField14.getText());
            statement.setInt(1, MEMBERID);
               set= statement.executeQuery();
          while(set.next())
          {
              MEMBERID=set.getInt(1);
              PASSWORD=set.getString(2);
              FIRSTNAME=set.getString(3);
              MIDDLENAME=set.getString(4);
              LASTNAME=set.getString(5);
              GENDER=set.getString(6);
              DATEOFBIRTH=set.getString(7);
              BLOODGROUP=set.getString(8);
              ADDRESS=set.getString(9);
              CITY=set.getString(10);
              STATE=set.getString(11);
              CONTACTNO=set.getString(12);
              EMAILID=set.getString(13);
              s1=set.getString(14);
              s2=set.getString(15);
              STARTINGDATE=set.getString(16);
              ENDINGDATE=set.getString(17);
              REMAININGDAYS=set.getString(18);
            
              if(s1.equals("1 MONTH"))
              {
                  jComboBox1.setSelectedIndex(1);
              }
              else if(s1.equals("3 MONTHS"))
              {
                  jComboBox1.setSelectedIndex(2);
              }
              else if(s1.equals("6 MONTHS"))
              {
                  jComboBox1.setSelectedIndex(3);
              }
              else if(s1.equals("12 MONTHS"))
              {
                  jComboBox1.setSelectedIndex(4);
              }
              
              
              jTextField22.setText(String.valueOf(MEMBERID));
               jTextField21.setText(PASSWORD);
               jTextField15.setText(FIRSTNAME);
               jTextField16.setText(MIDDLENAME);
               jTextField17.setText(LASTNAME);
               jTextField18.setText(GENDER);
               jTextField19.setText(DATEOFBIRTH);
               jTextField20.setText(BLOODGROUP);
               jTextField2.setText(ADDRESS);
               jTextField3.setText(CITY);
               jTextField4.setText(STATE);
               jTextField5.setText(CONTACTNO);
               jTextField6.setText(EMAILID);
                jTextField7.setText(STARTINGDATE);
                 jTextField8.setText(ENDINGDATE);
                  jTextField9.setText(REMAININGDAYS);
               
          } 
        }
        catch(SQLException e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_SEARCHActionPerformed

    private void LOADALLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOADALLActionPerformed
     
            try
            {
              statement=connection.prepareStatement("select * from memberdetails");
               
                   set= statement.executeQuery();
              while(set.next())
              {
                  Vector v3 = new Vector();

                  MEMBERID=set.getInt(1);
                  PASSWORD=set.getString(2);
                  FIRSTNAME=set.getString(3);
                  MIDDLENAME=set.getString(4);
                  LASTNAME=set.getString(5);
                  GENDER=set.getString(6);
                  DATEOFBIRTH=set.getString(7);
                  BLOODGROUP=set.getString(8);
                  ADDRESS=set.getString(9);
                  CITY=set.getString(10);
                  STATE=set.getString(11);
                  CONTACTNO=set.getString(12);
                  EMAILID=set.getString(13);
                  s1=set.getString(14);
                  s2=set.getString(15);
                  STARTINGDATE=set.getString(16);
                  ENDINGDATE=set.getString(17);
                  REMAININGDAYS=set.getString(18);

                  if(s1.equals("1 MONTH"))
                  {
                      jComboBox1.setSelectedIndex(1);
                  }
                  else if(s1.equals("3 MONTHS"))
                  {
                      jComboBox1.setSelectedIndex(2);
                  }
                  else if(s1.equals("6 MONTHS"))
                  {
                      jComboBox1.setSelectedIndex(3);
                  }
                  else if(s1.equals("12 MONTHS"))
                  {
                      jComboBox1.setSelectedIndex(4);
                  }


                  jTextField22.setText(String.valueOf(MEMBERID));
                   jTextField21.setText(PASSWORD);
                   jTextField15.setText(FIRSTNAME);
                   jTextField16.setText(MIDDLENAME);
                   jTextField17.setText(LASTNAME);
                   jTextField18.setText(GENDER);
                   jTextField19.setText(DATEOFBIRTH);
                   jTextField20.setText(BLOODGROUP);
                   jTextField2.setText(ADDRESS);
                   jTextField3.setText(CITY);
                   jTextField4.setText(STATE);
                   jTextField5.setText(CONTACTNO);
                   jTextField6.setText(EMAILID);

                   v3.add(sn);
                   v3.add(MEMBERID);
                   v3.add(FIRSTNAME);
                   v3.add(MIDDLENAME);
                   v3.add(LASTNAME);
                   v3.add(GENDER);
                   v3.add(DATEOFBIRTH);
                   v3.add(BLOODGROUP);
                   v3.add(ADDRESS);
                   v3.add(CITY);
                   v3.add(STATE);
                   v3.add(CONTACTNO);
                   v3.add(EMAILID);
                   v3.add(MEMBERSHIPTYPE);
                   v3.add(MEMBERSHIPTYPE);
                   v3.add(STARTINGDATE);
                   v3.add(ENDINGDATE);
                   v3.add(REMAININGDAYS);

                   v2.add(v3);

                   sn++;
              }

              dtm=new DefaultTableModel(v2, v1);
              jTable1.setModel(dtm);
            }
            catch(SQLException e)
            {
                e.printStackTrace();
            }
    }//GEN-LAST:event_LOADALLActionPerformed

    private void UPLOADPHOTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPLOADPHOTOActionPerformed
      FileDialog fd = new FileDialog(d,"Choose a File",FileDialog.LOAD);
       fd.setDirectory("C:\\");
       fd.setFile("*.jpg");
       fd.setVisible(true);
       String filename = fd.getFile();
        String imagename = filename;
         String filepath=fd.getDirectory()+filename;
         if(filename==null)
             System.out.println("You cancelled the choice..");
         else
             System.out.println("You chose "+ filepath);
         
         File file=new File(filepath);
         String doc_fol=FileSystemView.getFileSystemView().getDefaultDirectory().getPath();
         File file2= new File(doc_fol+"\\projec_images\\fitness");
         if(!file2.exists())
         {
             file2.mkdirs();
         }
         File file3 = new File(doc_fol+"\\projec_images\\fitness"+filename);
         try
         {
             BufferedImage bi=ImageIO.read(file);
             Image im=bi.getScaledInstance(jLabel19.getWidth(),jLabel19.getHeight(),Image.SCALE_SMOOTH);
          ImageIcon ic = new ImageIcon(im);
             jLabel19.setIcon(ic);
         }catch(IOException ex)
         {
             ex.printStackTrace();
         }
       System.out.println("Hello");
             
        CopyOption opt[]=new CopyOption[]{StandardCopyOption.REPLACE_EXISTING};
         
    try
    {
        Files.copy(file.toPath(),file3.toPath(),opt);
    }
    catch(IOException ex)
    {
        Logger.getLogger(ADMINMEMBERDETAILS.class.getName()).log(Level.SEVERE,null,ex);
    }
    }//GEN-LAST:event_UPLOADPHOTOActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADDDIET;
    private javax.swing.JButton ADDWORKOUT;
    private javax.swing.JButton EXIT;
    private javax.swing.JButton LOADALL;
    private javax.swing.JButton REGISTER;
    private javax.swing.JButton SEARCH;
    private javax.swing.JButton UPDATE;
    private javax.swing.JButton UPLOADPHOTO;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables


    @Override
    public void focusGained(FocusEvent fe) {
    }

    @Override
    public void focusLost(FocusEvent fe) {

        if(fe.getSource().equals(jTextField14))
        {
            try
            {
              statement=connection.prepareStatement("select * from memberdetails where MEMBERID=?");
                MEMBERID=Integer.parseInt(jTextField22.getText());
                statement.setInt(1, MEMBERID);
                   set= statement.executeQuery();
              while(set.next())
              {
                  Vector v3 = new Vector();

                  MEMBERID=set.getInt(1);
                  PASSWORD=set.getString(2);
                  FIRSTNAME=set.getString(3);
                  MIDDLENAME=set.getString(4);
                  LASTNAME=set.getString(5);
                  GENDER=set.getString(6);
                  DATEOFBIRTH=set.getString(7);
                  BLOODGROUP=set.getString(8);
                  ADDRESS=set.getString(9);
                  CITY=set.getString(10);
                  STATE=set.getString(11);
                  CONTACTNO=set.getString(12);
                  EMAILID=set.getString(13);
                  s1=set.getString(14);
                  s2=set.getString(15);
                  STARTINGDATE=set.getString(16);
                  ENDINGDATE=set.getString(17);
                  REMAININGDAYS=set.getString(18);

                  if(s1.equals("1 MONTH"))
                  {
                      jComboBox1.setSelectedIndex(1);
                  }
                  else if(s1.equals("3 MONTHS"))
                  {
                      jComboBox1.setSelectedIndex(2);
                  }
                  else if(s1.equals("6 MONTHS"))
                  {
                      jComboBox1.setSelectedIndex(3);
                  }
                  else if(s1.equals("12 MONTHS"))
                  {
                      jComboBox1.setSelectedIndex(4);
                  }


                  jTextField22.setText(String.valueOf(MEMBERID));
                   jTextField21.setText(PASSWORD);
                   jTextField15.setText(FIRSTNAME);
                   jTextField16.setText(MIDDLENAME);
                   jTextField17.setText(LASTNAME);
                   jTextField18.setText(GENDER);
                   jTextField19.setText(DATEOFBIRTH);
                   jTextField20.setText(BLOODGROUP);
                   jTextField2.setText(ADDRESS);
                   jTextField3.setText(CITY);
                   jTextField4.setText(STATE);
                   jTextField5.setText(CONTACTNO);
                   jTextField6.setText(EMAILID);

                   v3.add(sn);
                   v3.add(MEMBERID);
                   v3.add(FIRSTNAME);
                   v3.add(MIDDLENAME);
                   v3.add(LASTNAME);
                   v3.add(GENDER);
                   v3.add(DATEOFBIRTH);
                   v3.add(BLOODGROUP);
                   v3.add(ADDRESS);
                   v3.add(CITY);
                   v3.add(STATE);
                   v3.add(CONTACTNO);
                   v3.add(EMAILID);
                   v3.add(MEMBERSHIPTYPE);
                   v3.add(MEMBERSHIPTYPE);
                   v3.add(STARTINGDATE);
                   v3.add(ENDINGDATE);
                   v3.add(REMAININGDAYS);

                   v2.add(v3);

                   sn++;
              }

              dtm=new DefaultTableModel(v2, v1);
              jTable1.setModel(dtm);
            }
            catch(SQLException e)
            {
                e.printStackTrace();
            }
        }
    }
}
